// Pull in Next's ambient module declarations (notably `*.svg`, `*.png`, etc.)
// directly, instead of relying on the auto-generated `next-env.d.ts` — that
// file is gitignored and only regenerated by `next dev`/`next build`, so it is
// absent in a clean CI checkout, which breaks `tsc --noEmit` on SVG imports.
/// <reference types="next" />
/// <reference types="next/image-types/global" />

interface WheelEvent {
  readonly webkitDirectionInvertedFromDevice: boolean;
}
